### PR TITLE
Enable bazel-deps to fetch scala3 artifacts

### PR DESCRIPTION
**Pull request by DhashS**
it's a little silly, but this appears to work for me

### CODE REVIEW

**Comment by johnynek** [comment]
sorry for the latency on the review. I guess that is likely to be all that is required but I'm confused why the CI isn't running.

**Comment by johnynek** [comment]
can you please merge master in and see if we can run CI? If we can i will merge.

Thank you.

**Comment by DhashS** [comment]
@johnynek merged :)

**Comment by johnynek** [comment]
The CI failure isn't your fault. I merged and I'll fix that tomorrow.

**Pull request merged**
